name: ESLint

on:
  push:
    branches: [ "master" ]
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint
        run: |
          npm install eslint@8.25.0
          npm install eslint-config-airbnb 

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .js

        continue-on-error: true
